[personal]
name = "Ronak D. Shah"
location = "San Francisco, CA"
email = "roshah2023@gmail.com"
phone = "(412)-447-1666"
linkedin = "http://www.linkedin.com/in/ronakshah52"
webpage = "https://ronakdshah.github.io/"

[summary]
text = "Backend Engineer with 2+ years of experience in scalable systems and 5+ years in ML/data. Proven fintech impact through automation, tooling, and risk modeling."

[[experiences]]
company = "MerQube Inc"
role = "Backend Engineer"
duration = "Jun 2023 -- Present"
[[experiences.responsibilities]]
title = "Async Portfolio API"
description = "Designed and deployed an async Python API serving 100+ indices daily with real-time portfolio validation and scheduling; enabled automation for $600k ARR in index launches"

[[experiences.responsibilities]]
title = "Tax Rate Upload Service"
description = "Built a secure, extensible API for uploading and managing tax rates; improved compliance workflows and generated $60k in annual revenue"

[[experiences.responsibilities]]
title = "Pluggable QC Framework"
description = "Engineered a modular QC system executing 9000 checks/day across 8000 indices, ensuring distribution integrity and accelerating pre-release validation"

[[experiences.responsibilities]]
title = "File Monitoring Service"
description = "Developed a robust file monitor scanning SFTP endpoints and executing user-defined functions; integrated with Grafana and contributed $100k in annual recurring value"

[[experiences.responsibilities]]
title = "Index Configuration Tool"
description = "Created a bulk configuration update API reducing operational overhead by 80%; streamlined complex index editing workflows"

[[experiences.responsibilities]]
title = "Index Reporting Engine"
description = "Architected a scalable index reporting framework now supporting 6,800 indices; improved reporting latency and reduced manual intervention"

[[experiences.responsibilities]]
title = "Self-Service Index Launch"
description = "Delivered backend infra for client-driven options index deployment; cut turnaround time from 1 day to under 5 minutes"

[[experiences]]
company = "Affirm Inc"
role = "ML Engineer"
duration = "Oct 2021 -- Feb 2023"
[[experiences.responsibilities]]
title = "Merchant Risk API"
description = "Built and productionized a CatBoost-based API for real-time risk exposure estimation; improved loss accuracy by 20%"

[[experiences.responsibilities]]
title = "Onboarding Risk Model"
description = "Designed a GBM-based fraud detection model reducing onboarding-related fraud by 10%; integrated seamlessly with merchant approval pipeline"

[[experiences.responsibilities]]
title = "Graph-based Fraud Detection"
description = "Applied graph analytics to identify suspicious merchant clusters; led to a 4% reduction in financial loss"

[[experiences]]
company = "FedEx Ground"
role = "Data Engineer"
duration = "Jul 2020 -- Sep 2021"
[[experiences.responsibilities]]
title = "CFO Reporting Automation"
description = "Built automated dashboards reducing manual reporting time by 50%; ensured reliability and on-time delivery of performance insights"

[[experiences.responsibilities]]
title = "Weekly Metrics Pipeline"
description = "Designed a repeatable ETL pipeline for delivering weekly operations reports to stakeholders with improved data freshness"

[project]
name = "Portfolio Optimization"
details = [
    "Built a Flask-based tool with Clickhouse and CI/CD for portfolio optimization"
]

[project.research_paper]
title = "A unified framework for fast large-scale portfolio optimization"
link = "https://arxiv.org/abs/2303.12751"

[awards]
name = "Awards and Achievements"
details = [
    "Award of Honor for Outstanding Academic Excellence in AMS, Stony Brook University",
    "Graduate Certificate in Quantitative Finance from AMS, Stony Brook University",
]

[education]
[[education.degrees]]
degree = "MS Applied Math and Stats"
school = "Stony Brook University"
gpa = "3.95/4"
start_date = "Aug 2019"
end_date = "May 2021"

[[education.degrees]]
degree = "Bachelor of Technology"
school = "SVNIT Surat"
gpa = "8.51/10"
start_date = "Jul 2012"
end_date = "May 2016"

[skillset]
Languages = ["Python", "Go", "SQL", "JavaScript"]
"Frameworks / Backend" = ["Flask", "Pydantic", "Clickhouse", "FastAPI"]
Infrastructure = ["Docker", "AWS", "Ansible", "Git", "OpenLens", "Kubectl"]
"ML \\& Data" = ["Tree Models", "Convex Optimization", "Graph Algorithms", "Data Pipelines"]
