[personal]
name = "Ronak D. Shah"
location = "San Francisco, CA"
email = "roshah2023@gmail.com"
phone = "(631) - 428 - 0437"
linkedin = "http://www.linkedin.com/in/ronakshah52"
webpage = "https://ronakdshah.github.io/"

[summary]
text = "Backend Engineer with 2+ years of experience in scalable systems and 5+ years in ML/data. Proven fintech impact through automation, tooling, and risk modeling."

[[experiences]]
company = "MerQube Inc"
role = "Software Engineer - Backend"
duration = "Jun 2023 -- Present"

[[experiences.responsibilities]]
title = "Async Portfolio API"
description = "Architected async Python API for validating 100+ portfolios/day; enabled $600k ARR by automating index portfolio management"

[[experiences.responsibilities]]
title = "Index Platform API"
description = "Designed and scaled production-grade FastAPI backend on K8s, improving developer and operations experience on working with index code"

[[experiences.responsibilities]]
title = "Real Time System"
description = "Led real-time infra upgrades using time-based autoscaling and safe rollovers, improving system uptime and reducing deployment costs"

[[experiences.responsibilities]]
title = "File Monitoring Service"
description = "Built resilient file monitor service with user-defined workflows and integrated prometheus metrics and Grafana alerts, adding $100k in ARR"

[[experiences.responsibilities]]
title = "Multi Asset Framework"
description = "Engineered object oriented framework with abstract interfaces and modular components for multi-asset indices; enabled reusable, type-safe index development"

[[experiences.responsibilities]]
title = "Index Reporting Engine"
description = "Engineered scalable, standardized reporting pipeline for 6,800+ indices. Implemented robust data validation using pydantic to ensure accuracy and reliability"

[[experiences.responsibilities]]
title = "Self-Service Index API"
description = "Delivered client-facing API for index creation and backtesting; enabled near real-time onboarding of custom index strategies"

[[experiences]]
company = "Affirm Inc"
role = "Software Engineer - Quantitative Risk"
duration = "Oct 2021 -- May 2023"
[[experiences.responsibilities]]
title = "Merchant Risk API"
description = "Built and productionized a CatBoost-based API for real-time risk exposure estimation; improved loss accuracy by 20%"

[[experiences.responsibilities]]
title = "Onboarding Risk Model"
description = "Designed a GBM-based fraud detection model reducing onboarding-related fraud by 10%; integrated seamlessly with merchant approval pipeline"

[[experiences.responsibilities]]
title = "Graph-based Fraud Detection"
description = "Applied graph analytics to identify suspicious merchant clusters; led to a 4% reduction in financial loss"

[[experiences]]
company = "FedEx Ground"
role = "Software Engineer - Data Science"
duration = "Jul 2020 -- Sep 2021"
[[experiences.responsibilities]]
title = "CFO Reporting Automation"
description = "Built automated dashboards reducing manual reporting time by 50%; ensured reliability and on-time delivery of performance insights"

[[experiences.responsibilities]]
title = "Weekly Metrics Pipeline"
description = "Designed a repeatable ETL pipeline for delivering weekly operations reports to stakeholders with improved data freshness"

[project]
name = "Portfolio Optimization"
details = [
    "Built a Flask-based tool with Clickhouse and CI/CD for portfolio optimization"
]

[project.research_paper]
title = "A unified framework for fast large-scale portfolio optimization"
link = "https://arxiv.org/abs/2303.12751"

[awards]
name = "Awards and Achievements"
details = [
    "Award of Honor for Outstanding Academic Excellence in AMS, Stony Brook University",
    "Graduate Certificate in Quantitative Finance from AMS, Stony Brook University",
]

[education]
[[education.degrees]]
degree = "MS Applied Math and Stats"
school = "Stony Brook University"
gpa = "3.95/4"
start_date = "Aug 2019"
end_date = "May 2021"

[[education.degrees]]
degree = "Bachelor of Technology"
school = "SVNIT Surat"
gpa = "8.51/10"
start_date = "Jul 2012"
end_date = "May 2016"

[skillset]
Languages = ["Python", "Go", "SQL", "JavaScript"]
"Frameworks / Backend" = ["Flask", "Pydantic", "Clickhouse", "FastAPI"]
Infrastructure = ["Docker", "AWS", "Ansible", "Git", "OpenLens", "Kubectl"]
"ML \\& Data" = ["Tree Models", "Convex Optimization", "Graph Algorithms", "Data Pipelines"]
